title: "Tower Dungeon"
description: "A thrilling manga about adventurers exploring a mysterious tower dungeon"
primary_language: "en"
status: "ongoing"  # "ongoing", "complete", or "hiatus"

# Manga-specific configuration
chapter_type: "manga"  # Sets all chapters as manga by default
reading_direction: "ltr"  # "ltr" (left-to-right) or "rtl" (right-to-left)

# Manga reader defaults
manga_defaults:
  view_mode: "single"          # "single", "double", "scroll", or "scroll_double"
  cover_separate: true         # First page shown separately in double/scroll_double modes
  image_scaling: "fit_screen"  # "fit_screen", "fit_width", "original"
  zoom_level: 100             # Default zoom percentage
  preload_pages: 3            # Number of pages to preload
  page_turn_area: "right_half" # "left_half", "right_half", "full_page"

# Image processing settings
image_processing:
  skip_compression: true      # Skip image compression for manga pages

# Story genre/theme tags
tags: ["manga", "adventure", "dungeon", "fantasy", "action"]

# Story metadata display settings
metadata:
  # Update schedule information (optional)
  update_schedule: "Weekly on Sundays"
  
  # License information (optional)
  license: "Copyrighted"  # Options: "Copyrighted", "CC0", "Public Domain", "CC BY", "CC BY-SA", etc.
  
  # Display settings - control what metadata is shown on TOC
  display:
    show_update_schedule: true      # Show update schedule if provided
    show_license_info: true         # Show license information if provided
    show_author_contributions: true # Show calculated author contributions
    show_last_updated: true         # Show calculated last chapter update date
    show_story_stats: true          # Show calculated story statistics

# Story arcs and chapters
arcs:
  - title: "Volume 1: The Tower's Secret"
    chapters:
      - id: "chapter-1"
        title: "Chapter 1: The Sovereign's Secret Sin"
      - id: "chapter-2"
        title: "Chapter 2: The Tower's First Trial"

# Social media settings
social_embeds:
  image: "/static/images/tower-dungeon-social.jpg"
  description: "Follow the epic adventure in this dungeon-crawling manga"
  keywords: ["manga", "adventure", "dungeon", "fantasy", "webcomic"]

# SEO settings
seo:
  allow_indexing: true
  meta_description: "Read Tower Dungeon - an epic fantasy manga about mysterious tower exploration"

# Downloads configuration  
downloads:
  epub_enabled: false    # Manga chapters don't work well as EPUB
  include_arcs: false

# Footer for this story
footer:
  copyright: "© 2025 Tower Dungeon - Original work by Manga Artist"
  links:
    - text: "Support the Artist"
      url: "https://ko-fi.com/pyramid"
    - text: "Original Source"
      url: "http://www.ocwn.net/"